### PR TITLE
Fix Note:Cursor doesn't change on select

### PR DESCRIPTION
**Pull request by pushkov-fedor**
Issue #600
Tried change context by dispatching setCursor in onFocus event of Note component. It solves the issue, but this action sets focus on parent Thought of the Note. As i see, dispatch action triggers render of Thought component, where isEditing is computed by`isEditing = equalPath(cursorBeforeEdit, thoughtsResolved)`, i think it is the reason why Thought, parent of Note, is getting focused. We need somehow prevent this focus event, do you have any ideas?

Timeout with focus was added just for test

### CODE REVIEW

**Comment by pushkov-fedor** [comment]
@raineorshine  I added additional check before `setSelection`, now Thought isn't getting focus after click on Note component. I found one bug. It works pretty well, when we have Note with text. But if we click/tap on empty note, cursor will be set and reset immediately. I'm trying to find the reason of this behavior. What do you think about this?

**Comment by raineorshine** [comment]
> I found one bug. It works pretty well, when we have Note with text. But if we click/tap on empty note, cursor will be set and reset immediately. I'm trying to find the reason of this behavior. What do you think about this?

Do you have Redux DevTools? I'm seeing two calls to `setCursor` in this case. The first has `noteFocus: true` and the next does not. I don't know what is calling the `setCursor` but if you do a stack trace I'm sure you can find out. Perhaps it's the blur event.

I'm also noticing a bug in `dev` where the cursor disappears when a note is first added. I think it has to do with `cursorBeforeEdit` not being updated when the focus changes between the thought and its note. We can create a separate issue for that, but I want to make sure it's not interfering with your work on this issue.

**Comment by pushkov-fedor** [comment]
@raineorshine Okay, i'll fix them, thanks for review. Can i log extra 0.5 hour for this? Is it okay?

**Comment by raineorshine** [comment]
Yes, an extra 1-2 hours is fine since it was a little more complicated than expected.

**Comment by pushkov-fedor** [comment]
Fixed, #600 is also here

**Comment by pushkov-fedor** [comment]
@raineorshine It's so strange. I've tested it again on local and it works.

- thought
[note] **(cursor is here)**

After click on Note button:

- thought **(cursor is here)**
[note]

And reverse for the next situation. Please tell me, if i don't understand something about desired behavior. I've tested in on PC and Android mobile device.

**Comment by raineorshine** [comment]
Okay, thanks for confirming! It must be a platform issue. I'll see if I can fix up the issues on Desktop and Mobile Safari. Then you can test them out again on your platforms. What desktop browser are you using btw?

**Comment by raineorshine** [comment]
Okay, working now on my end. Will you test 325e640 at your convenience? Thanks, and have a good holiday!

**Comment by pushkov-fedor** [comment]
It's Chrome on both devices. Yeah, i will test it tomorrow on mobile and PC.

**Comment by pushkov-fedor** [comment]
I've tested it. It works on both mobile and desktop Chrome

**Comment by raineorshine** [comment]
Thanks! I'll merge soon.

**Pull request merged**
