### PR TITLE
Fix the issue with superscript not rendering when load.

### PR DESCRIPTION
**Pull request by ruchijn**
Fixes: #1419 

Before:
superscript_load_before

After:
superscript_load_after

### CODE REVIEW

**Review by raineorshine — CHANGES_REQUESTED** [review]
It works!

We just need to subscribe to only the relevant `Lexeme`. If you subscribe to `thoughtIndex`, then all `ThoughtAnnotations` will re-render every time a `Lexeme` changes.

**Comment by ruchijn** [comment]
How do I subscribe to relevant `Lexeme`? When you said that I thought you meant `thoughtIndex`. 🤔

**Comment by raineorshine** [comment]
> How do I subscribe to relevant `Lexeme`? When you said that I thought you meant `thoughtIndex`. 🤔

`thoughtIndex` is of type `Index<Lexeme>`. It contains every `Lexeme` in memory, including many that are not visible. You don't want a superscript re-rendering unless the actual number for that superscript has changed, and the actual number is determined by a single `Lexeme`. For example, if the thought "apples" appears twice in the full thoughtspace, the `Lexeme` "apple" will contain two contexts. If a different `Lexeme`, e.g. "orange" changes, we don't need to re-render the "apple" superscript.

By subscribe, I mean return from `mapStateToProps`. Whether we use `mapStateToProps`, `useSelector`, or another hook, we are effectively subscribing the component to different conditions that affect when it gets rendered. This is also called reactive programming.

Notice where `numContexts` is being calculated currently in `ThoughtAnnotation`. It calls `getContexts` with `store.getState()` directly, which will not trigger a re-render when the `Lexeme` changes.

Let me know if you need additional clarification!

**Review by raineorshine — CHANGES_REQUESTED** [review]
Since your selector returns a new object reference (the array returned by `getContexts`), it will re-render on every state change. If you react to `numContexts` it won't suffer the same problem, since equal numbers are strictly equal.

**Comment by ruchijn** [comment]
I tested with `getContexts` and `StaticSuperscript`  doesn't re-render. But I will change as per your suggestion.

**Comment by raineorshine** [comment]
> I tested with `getContexts` and `StaticSuperscript` doesn't re-render.

Yes, but `ThoughtAnnotation` re-renders on every state change. Plus, it should be clear that it re-renders every time based on principle. It is returning a new object reference every time.

> And if I react to `numContexts`, then it will not re-render even when state changes.

I'm not sure what you mean. If you react to `numContexts`, then it will re-render when `numContexts` changes. We don't want it to re-render when other parts of the state change.

> Please let me know in case I am missing something. I tried with `numContexts` and it didn't re-render even when it was supposed to.

`mapStateToProps` and `useSelector` don't really work together. If `mapStateToProps` does not change its output, then `render` will not be called at all, and `useSelector` cannot re-calculate. I'm not sure, but my guess is that this is why you weren't seeing it re-render. You need to use one or the other.

**Comment by raineorshine** [comment]
> `mapStateToProps` and `useSelector` don't really work together. If `mapStateToProps` does not change its output, then `render` will not be called at all, and `useSelector` cannot re-calculate. I'm not sure, but my guess is that this is why you weren't seeing it re-render. You need to use one or the other.

I was wrong about this. It appears that `useSelector` works fine when it only uses its internal `state`.

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
