### PR TITLE
fix ios cursor drift issue

### LINKED ISSUE #4: [iOS] Caret drifts during navigation
When navigating, the content is smoothly translated, but the caret drifts.

## Current Behavior

On iOS, the caret drifts out of place during the animation. 

Video 1:
https://github.com/cybersemics/em/assets/750276/931e766d-291c-495b-83b7-bebde4625dcb

Video 2:
https://youtu.be/Poo61duk41w

## Expected Behavior

The browser cursor should stay in place (not move relative to its contenteditable).

If this is a bug in Safari and there is no fix, see if you can hide the caret during the transition (without removing the selection, closing the keyboard, or preventing the user from typing).

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes #4

### CODE REVIEW

**Comment by raineorshine** [comment]
I just missed your submission! As of this morning I will be on a meditation retreat for the next week and won’t have access to my computer or wallet to pay out the bounty.

Looking forward to testing your submission when I get back on December 10th! Thanks!

**Comment by mul1sh** [comment]
@raineorshine, no worries, thanks for alerting me and have a good retreat. Talk on the 10th 🙂

**Comment by raineorshine** [comment]
Thanks for the submission! I am seeing two main issues:

1. Sometimes the selection jumps back to the bullet
2. Sometimes the transition animation of the thoughts sliding left is skipped 

Video capture: https://youtu.be/Tu9drL743iU

**Comment by mul1sh** [comment]
@raineorshine unfortunately the left to right animation has to be skipped for the cursor to stop drifting.

The reason why this translate animation is skipped in one direction in my code is because i'm using the property `animation-fill-mode: forwards;` which means it only retains the style values set by the last keyframe of the transform animation.

This was intentional on my part as this was the only way I could stop the cursor from drifting because the drifting was caused by a webkit bug in iOS which still hasn't been fixed yet in iOS 13, but will be released in the near future according to this [thread](https://bugs.chromium.org/p/chromium/issues/detail?id=899130#c11).

The bug is basically because iOS webkit [doesn't yet support](https://bugs.chromium.org/p/chromium/issues/detail?id=899130#c21)the Web Animations CSS Integration feature which is what allows smooth animations in OSX chrome & safari which both use webkit under the hood.

So once this feature is enabled in iOS, then all the animations will work has intended without any more issues.

**Comment by raineorshine** [comment]
Thank you for the explanation. It is good to know what is causing it at least.

I appreciate your attempt at a workaround, although it is not what I am looking for. I would rather have the cursor drift with the correct translate animation than the other way around.

**Pull request closed without merging**
