### PR TITLE
Expand thought that ends in “:” character

### PR DESCRIPTION
**Pull request by enukeabhi**
Thoughts ending in  ':' are expanding by default, except thoughts at root level.
Looking how we can expand thought at root level.

### CODE REVIEW

**Comment by raineorshine** [comment]
Please name issues with a descriptive phrase rather than an issue number. The issue number should go in the first comment.

**Comment by raineorshine** [comment]
This is a great start! Just the following from what I can see:

- [ ] Expand thoughts that end with `:` in root
- [ ] When cursor is on a thought that end with `:`, do not collapse other visible thoughts that end with `:`

**Comment by enukeabhi** [comment]
> This is a great start! Just the following from what I can see:
> 
> * [ ]  Expand thoughts that end with `:` in root
> * [ ]  When cursor is on a thought that end with `:`, do not collapse other visible thoughts that end with `:`

Thanks!
Working on the same will update you once done.

**Comment by raineorshine** [comment]
@enukeabhi Hi, I recommend taking a close look at my solution in 4783c7e. The additional argument was unnecessary once `expandThoughts` was called during `loadLocalState` and `setCursor`. This approach is strongly preferable to avoid the special case.

The other key was using `contextOf` to calculate `expandThoughts` for the context of the current thought as opposed to the current thought itself, thus allowing siblings to expand.

**Comment by raineorshine** [comment]
@enukeabhi Okay, it was a little more complicated than that, but you can see the additional changes in 604f94a. I had to move the `contextOf` call internal to `expandThoughts` otherwise it wasn't expanding only-children properly.

**Pull request merged**
