### PR TITLE
Bump react-dnd version from v14 to v15

### PR DESCRIPTION
**Pull request by Zubair286**
#1839

### CODE REVIEW

**Comment by Zubair286** [comment]
Seems we need to bump the version upto v16 to get rid of the error, probably in that version the directory structure.

**Comment by Zubair286** [comment]
Yes, I as just doing that.

**Review by raineorshine — CHANGES_REQUESTED** [review]
Looks good, thanks.

Please upgrade to `v15.1.2` in this PR. There's no point upgrading to a lesser version when there are backwards-compatible bug fixes and improvements at the same major version level. (That's the whole point of semver.)

**Comment by Zubair286** [comment]
There seems to be a bug in v15.1.2, which is related to react version, v15.1.2 working with React 18 seems to be giving the below error, searching the internet it seems to work fine with React 17, on react-dnd v16 the issue seems to be fixed.

```
[vite-plugin-pwa:build] Missing "./jsx-runtime.js" specifier in "react" package
    at e (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:45942:25)
    at n (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:45942:627)
    at o (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:45942:1297)
    at resolveExportsOrImports (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:46563:18)
    at resolveDeepImport (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:46586:25)
    at tryNodeResolve (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:46351:16)
    at Object.resolveId (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:46101:19)
    at file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19892:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19792:28)
    at async resolveId (file:///home/hashlogic/Desktop/cyberem/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18466:26)
error Command failed with exit code 1
```

**Comment by Zubair286** [comment]
I've seen the fixes but they all seems to be for webpack, and I tried setting the alias for `react/jsx-dev-runtime` in vite.config.js and it does not work.

**Comment by raineorshine** [comment]
Okay, thanks for trying. Strange they didn't release a patch for that before bumping the major. If I were them, I wouldn't want my latest minor version to be broken.

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
