### PR TITLE
Remove blur event on note component

### LINKED ISSUE #846: Caret disappears after new thought from note
em - 846 mov

## Steps to Reproduce

1. Create `a`
2. Create a new note (Control + Alt + n)
3. Hit Enter

## Current Behavior

Caret disappears

## Expected Behavior

Caret should move to the new thought

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #846 

@raineorshine I don't think we need to clear selection on blur event of note component. As soon new thought sets selection, blur event from note clears it.

### CODE REVIEW

**Comment by shresthabijay** [comment]
> Before deleting the `onBlur` we need to confirm that the original purpose of it is no longer needed. It was added in [06b6583](https://github.com/cybersemics/em/commit/06b65838ce51c2d41fd6826e52926ca4d7a74863). Please identify the corresponding PR and issue for that commit and confirm that removing the `onBlur` will not cause a regression. Consult the author of the commit (@pushkov-fedor) as needed. Thanks!

Sure. I will do that.

**Comment by shresthabijay** [comment]
@pushkov-fedor Can you let me know the original purpose of calling `clearSelection` to `NoteComponent` `onBlur` event ?

**Comment by pushkov-fedor** [comment]
> @pushkov-fedor Can you let me know the original purpose of calling `clearSelection` to `NoteComponent` `onBlur` event ?
@shresthabijay 
From my PR:
`It works pretty well, when we have Note with text. But if we click/tap on empty note, cursor will be set and reset immediately. `

We had strange cursor behavior there, and this onBlur fixed it. I've tested Note component on dev without `onBlur` handler. It works. Feel free to remove it

**Comment by raineorshine** [comment]
@pushkov-fedor Can you provide a link to the PR so we have a record here? Thanks!

**Comment by pushkov-fedor** [comment]
> @pushkov-fedor Can you provide a link to the PR so we have a record here? Thanks!

Sure! https://github.com/cybersemics/em/pull/610#issuecomment-621809351

**Pull request merged**
