### PR TITLE
Selectors

### PR DESCRIPTION
**Pull request by raineorshine**
#483

### CODE REVIEW

**Comment by raineorshine** [comment]
@anmolarora1 First step is moving the selectors out of `útil` and standardizing the interface. Let me know if I’m on the right track here. Thanks!

**Comment by anmolarora1** [comment]
> @anmolarora1 First step is moving the selectors out of `util` and standardizing the interface. Let me know if I’m on the right track here. Thanks!

@raineorshine It seems like a good approach. 
I noticed some instances where the state is optionally being passed or retrieved via `store.getState()`. Now that we're having selectors, I think we should refrain from using optional comments wherever possible.

**Comment by raineorshine** [comment]
I agree. Thanks!

**Comment by raineorshine** [comment]
Closing for #524

**Pull request closed without merging**
