### PR TITLE
Split sentence on comma if period is not present

### LINKED ISSUE #1041: Split sentences should split on comma when there are no periods
## Steps to Reproduce

1. Create thought "one, two, three"
2. Activate "Split Sentences"

## Current Behavior

Cannot split sentences.

## Expected Behavior

- one
- two
- three

## Notes

Thoughts with a combination of periods and commas should be split on periods only. 

e.g. Activating Split Sentences on "one. two, three." should yield:

- one.
- two, three.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1041

# Changes
- Seperate splitting value logic to a separate `splitSentence` logic. 
- Add test for the changes.

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine Please review the changes.

**Review by raineorshine — CHANGES_REQUESTED** [review]
Looks great! I thought of a couple small tweaks I wanted to make to the requirements:

- If a thought with a mix of commas and periods has only one period and it's the last character, remove it and split on comma
- Split on semicolon just like period

**Comment by shresthabijay** [comment]
> * If a thought with a mix of commas and periods has only one period and it's the last character, remove it and split on comma

What if there are other split characters too in the string ? For example `One!, Two, Three.`

**Comment by shresthabijay** [comment]
> * Split on semicolon just like period

Do you mean the same behavior with mix of commas and semilcon ?

**Comment by raineorshine** [comment]
> > * If a thought with a mix of commas and periods has only one period and it's the last character, remove it and split on comma
> 
> What if there are other split characters too in the string ? For example `One!, Two, Three.`

Normally if there are a mix of split characters, it will split on period. However if the period is at the end, you should remove the period and split on comma. Does that answer?

**Comment by shresthabijay** [comment]
> Normally if there are a mix of split characters, it will split on period.

Current behavior is that on mix of split characters, it will split on every split character. For example: `One?Two!Three.Four` will split into `['One.'. 'Two.', 'Three.', 'Four.']` . So if there is a string such as `One,Seven?Two!Three.`, then it should split as `['One', 'Seven?Two!Three']`. Is this correct ?

**Comment by raineorshine** [comment]
> > Normally if there are a mix of split characters, it will split on period.
> 
> Current behavior is that on mix of split characters, it will split on every split character.

That is correct for thoughts without commas.

> So if there is a string such as `One,Seven?Two!Three.`, then it should split as `['One', 'Seven?Two!Three']`. Is this correct ?

No, hard split characters should always take precedence over commas. So it would split as `One,Seven?', 'Two!', 'Three.'`.

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
