### PR TITLE
Update bottom Breadcrumbs position to be :fixed

### PR DESCRIPTION
**Pull request by aqkhan**
Referenced to #391

### CODE REVIEW

**Comment by raineorshine** [comment]
Oops! I messed up the requirements. It's the bottom breadcrumbs that should be position: sticky, not the entire footer. Could you redo this according to this new requirement? Thank you!

**Comment by aqkhan** [comment]
Screenshot 2020-03-02 at 10 42 06 PM
Just to be sure, are you referring to these?

**Comment by raineorshine** [comment]
Yes

**Comment by aqkhan** [comment]
Thanks. I'll the updates accordingly.

**Comment by aqkhan** [comment]
@raineorshine The code has been updated to meet the updated requirements.

**Comment by aqkhan** [comment]
`<NavBar>` has been wrapped into `Scale`.

**Pull request merged**
