### PR TITLE
Fix arrow up arrow down for multiline thought

### PR DESCRIPTION
**Pull request by incora-dev**
#550

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks! We're close. just one case that is incorrect.

- [x] ArrowDown from line 1
- [ ] ArrowDown from line 2
- [x] ArrowUp from line 2

## Steps to Reproduce

ArrowDown on the following:

```
- This is a thought that 
  is |now wrapping.
- Test
```

## Expected Behavior

```
- This is a thought that 
  is now wrapping.
- Tes|t
```

## Current Behavior

```
- This is a thought that 
  is now wrapping.|
- Test
```

## Notes

In this case, the cursor should go to the next thought, like the current behavior. Getting the exact offset can be done either in this issue or in #333. Either way it should not be moving the selection to the end of the element.

**Comment by incora-dev** [comment]
@raineorshine The main problem of this task is detecting a caret position in contenteditable block. Ideally, getting line number and offset from the left side (but I didn't found any good solution for that). Maybe you have some ideas have we can solve it

I have written some function that checks if cursor on the first or last line of contenteditable block, but it doesn't work pretty good 
```
export const isCursorOnEdgeMultiline = () => {
  const range = getSelection().getRangeAt(0)
  const span = document.createElement('span')
  range.insertNode(span)
  const { offsetTop, parentNode, parentElement, offsetHeight } = span
  const isTop = ((offsetTop - parentNode.offsetTop) === 0)
  const isBottom = ((offsetTop - parentElement.offsetTop + offsetHeight + 20) >= parentElement.offsetHeight)
  span.parentNode.removeChild(span)
  return { isTop, isBottom }
}
```

**Comment by raineorshine** [comment]
Yes, that sounds right. I haven't worked with calculating selection position before, so I don't have any ideas right now. I would assume that people have posted similar problems on StackOverflow.

**Comment by incora-dev** [comment]
What exactly is wrong? Could you confirm that case `ArrowDown from line 2` still has the same behavior?

**Comment by raineorshine** [comment]
Sorry, I should have explained more. Here's what I am seeing:

- [ ] ArrowUp from line 1 should move to previous sibling
- [x] ArrowUp from line 2 should move up a line (default browser behavior)
- [x] ArrowDown from line 1 should move down a line (default browser behavior)
- [x] ArrowDown from line 2 should move to next sibling

So the issue was fixed, but there is a regression which causes the selection to go to the beginning of line 1 instead of to the previous sibling when the selection is on line 1 and you hit ArrowUp.

**Comment by incora-dev** [comment]
@raineorshine To handle first case I need 3 hours more as it's a bit different behavior as arrow down. For arrow down I just needed to move cursor to the next thought but here I also need to set it in the specific position.

**Comment by raineorshine** [comment]
@incora-dev Let's go with a simpler solution where ArrowUp from line 1 moves the selection to the beginning of the previous sibling (current `dev` behavior). Then we can avoid having to do the specific position calculations.

This is what WorkFlowy does, so it's not a bad solution. I updated the [list of requirements](https://github.com/cybersemics/em/pull/558#issuecomment-625900691).

**Comment by raineorshine** [comment]
Looks good, thank you!

**Pull request merged**
