### PR TITLE
Jest + Enzyme setup

### PR DESCRIPTION
**Pull request by mekanix**
The test fails because `document` and `window` objects in test env don't have all properties that they have in the browser, but the test setup itself is good.

### CODE REVIEW

**Comment by raineorshine** [comment]
Is the `__tests__` folder conventional, or a name you chose? Just wondering about all the underscores.

**Comment by raineorshine** [comment]
(FYI You can open a [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to allow me to see your initial work but indicate that you are still working on it.)

**Comment by mekanix** [comment]
The `__test__` directory is per [Jest default config](https://jestjs.io/docs/en/configuration.html#testmatch-arraystring).

Thank you for pointing out Draft PR, I didn't know about it! :o)

**Comment by mekanix** [comment]
The setup for testing is finished. There are `beforeAll` / `afterAll` functions which run the actual setup for tests, regardless if testing succeeded or not. There are also `beforeEach` and `afterEach` Jest functions which setup and tear down before/after every test. Also, Jest comes with support for mocking functions and modules.

Useful links:
[Setup and Teardown](https://jestjs.io/docs/en/setup-teardown.html)
[Globals](https://jestjs.io/docs/en/api.html)
[Mocking Functions and Modules](https://jestjs.io/docs/en/mock-functions.html)

**Pull request merged**
