### PR TITLE
Replaces typedoc-plugin-external-module-name with a forked version

### LINKED ISSUE #889: docs script fails
The `docs` script is failing due to a recent update, possibly #886.

Please confirm which commit broke the script, and remediate.

https://github.com/cybersemics/em/runs/1277664876

### PR DESCRIPTION
**Pull request by anmolarora1**
fixes #889

### CODE REVIEW

**Comment by anmolarora1** [comment]
@raineorshine Though the `docs` script error has been fixed in the forked version of the plugin, the docs aren't being generated correctly. It's probably with the configuration mismatch between the plugin and the `typedoc` itself. 
I'm looking into their documentation to figure out if we need to make any changes to our configuration.

**Comment by raineorshine** [comment]
I'll hold off until merging until you either find a resolution or we decide to revert.

**Comment by anmolarora1** [comment]
> I'll hold off until merging until you either find a resolution or we decide to revert.

@raineorshine  Though the error is fixed with our recent changes, I've found some compatibility issues with the plugin and `typedoc v019.2` which prevents the docs from being generated as expected.
[The function](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L70) that is supposed to trigger the [custom name mapper](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L136) function isn't being called at all. 
We can dig deep into this to find out if it's an issue with the `typedoc` or the `plugin`, but unless there's a strong reason for updating `typedoc`, I'd suggest we should probably revert the typedoc version for now, until we get a response from the plugin's creator on [this issue](https://github.com/christopherthielen/typedoc-plugin-external-module-name/issues/548)

**Comment by raineorshine** [comment]
> [The function](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L70) that is supposed to trigger the [custom name mapper](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/5af43c4189123b63dee3065392a06a7ea5d28126/typedoc-plugin-external-module-name.ts#L136) function isn't being called at all.
> We can dig deep into this to find out if it's an issue with the `typedoc` or the `plugin`, but unless there's a strong reason for updating `typedoc`, I'd suggest we should probably revert the typedoc version for now, until we get a response from the plugin's creator on [this issue](https://github.com/christopherthielen/typedoc-plugin-external-module-name/issues/548)

Great, thank you for looking into this! Since it's not a trivial change, I agree we should wait until the developer responds before doing additional work.

In the mean time, let's revert typedoc and move on. Thanks!

**Pull request closed without merging**
