### PR TITLE
Restore cursor selection aftter toolbar click

### LINKED ISSUE #1233: Edit mode lost after executing command
Tested on mobile Safari. Unknown if reproducible in emulation mode on desktop. 

## Steps to Reproduce

1. Create thought `a` and stay in edit mode
2. Tap the Pin button 

## Current Behavior

Edit mode is disabled

## Expected Behavior

Edit mode should stay enabled after any command. 

You can use [asyncFocus](https://github.com/cybersemics/em/blob/dev/src/util/asyncFocus.ts) on Safari before activating the command to allow the selection to be set outside of a handler.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1233

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine  Please review the changes. Thanks!

**Comment by raineorshine** [comment]
This causes a regression unfortunately:

```
- a
  - [empty thought]
```

Backspace to delete the empty thought. The keyboard is still up by the caret has disappeared and typing has no effect.

Can we discuss the cause of the problem (in #1233) and the nature of the proposed solution (here)? It looks complex, and it tightly couples the Toolbar to the thought structure.

**Review by raineorshine — CHANGES_REQUESTED** [review]
This causes a regression unfortunately:

```
- a
  - [empty thought]
```

Hit backspace to delete the empty thought. The keyboard is still up but the caret has disappeared and typing has no effect.

Can we discuss the cause of the problem (in #1233) and the nature of the proposed solution (here)? I am hesitant to tightly couple the Toolbar to the thought structure and I would like to understand the problem better.

**Comment by shresthabijay** [comment]
@raineorshine I found a quite easy and simple solution. I had no idea preventing the default `mouseDown` event also prevented blur. I also have made some changes to `splitResult` because of the previous implementation. But we can keep it. Please review the changes. Thanks!

**Review by raineorshine — APPROVED** [review]
Excellent work!

**Pull request merged**
