### PR TITLE
Feature/split and combine reducers #57

### PR DESCRIPTION
**Pull request by miladkdz**
rebased with the other PR(#84)
I just couldn't get the code you mentioned(https://stackoverflow.com/a/57009738/480608) to work:

```
**/src/reducers/index.js**

// require all modules on the path and with the pattern defined
const req = require.context('./', true, /Reducer.js$/);

const modules = req.keys().map(req);

// export all modules
export default modules
```

```
**/src/store.js**

import { appReducer } from './reducers'
```

### CODE REVIEW

**Comment by raineorshine** [comment]
Great work! I think you want this line as-is: 

```
const req = require.context('./', true, /.js$/)
```

Because we are trying to pull in all reducer files in the /reducer folder in the same statement. I have not tried it myself though so just use manual imports if you cannot get it to work. 

Regarding the circular references, try moving the shared dependencies (initialState, syncOne, and syncRemoteData I believe) into their own file (perhaps `store-util.js`). Then the reducer files will not have to import `store.js`.

If all of that works, you can move each individual reducer into its own file.

**Comment by miladkdz** [comment]
Thanks for clarification. I’ll work on it on Sunday.

**Comment by raineorshine** [comment]
The new reducer files should be:

```
reducers/status.js
reducers/authenticate.js
reducers/clear.js
reducers/render.js
reducers/data.js
reducers/tutorialStep.js
reducers/delete.js
reducers/newItemSubmit.js
reducers/setCursor.js
reducers/cursorHistory.js
reducers/existingItemChange.js
reducers/existingItemDelete.js
reducers/existingItemMove.js
reducers/codeChange.js
reducers/onPaste.js
reducers/helperComplete.js
reducers/helperRemindMeLater.js
reducers/expandContextItem.js
reducers/showHelperIcon.js
reducers/showHelper.js
reducers/editing.js
reducers/toggleContextView.js
reducers/toggleCodeView.js
reducers/search.js
reducers/cursorBeforeSearch.js
reducers/dragInProgress.js
reducers/selectionChange.js
reducers/searchLimit.js
```

**Comment by raineorshine** [comment]
Fixes #57

**Comment by raineorshine** [comment]
@miladkdz There were some merge conflicts I had to sort through, but your changes have been integrated into the repository. Thank you!

**Pull request closed without merging**
