### PR TITLE
=let style variables

### PR DESCRIPTION
**Pull request by raineorshine**
#612

Add support for defining scoped `=style` variables with `=let`.

```js
- =let
  - =h1
    - =style
      - fontSize
        - 30px
      - fontWeight
        - bold
- Header
  - =h1
```

will apply the `=h1` styles to the `Header`  as if it was:

```js
- Header
  - =style
    - fontSize
      - 30px
    - fontWeight
      - bold
```

### CODE REVIEW

**Comment by onurpolattimur** [comment]
It is really a perfect feature Raine! 

Just a few question;
- What do we expect when users enter our metaprogramming keys as a variable name? For example, when the user enters =sort instead of =h1 while defining a variable, the app will crash.

- Also, the style is applied to thought '=let' itself. Do we want this?
Here is a screenshot: 
image

**Comment by raineorshine** [comment]
> It is really a perfect feature Raine!

Thank you! **em** has so much potential once we start adding more programmability.

> * What do we expect when users enter our metaprogramming keys as a variable name? For example, when the user enters =sort instead of =h1 while defining a variable, the app will crash.

User-defined variables should probably be namespaced so they do not interfere with native metaprogramming attributes.

> * Also, the style is applied to thought '=let' itself. Do we want this?

It should only be applied to `=let/=h1` and `onur` (and arguably only `onur`, since `=let/=h1` is just the definition. It is happening because the `=let` expression is being parsed and applied to its containing context, with of course includes `=let` itself. I didn't know it was possible to have a function definition and application at the same time 😂.

**Comment by onurpolattimur** [comment]
> User-defined variables should probably be namespaced so they do not interfere with native metaprogramming attributes.

Yes, we should prevent that users enter our metaprogramming attibute as a variable name.

> It should only be applied to =let/=h1 and onur (and arguably only onur, since =let/=h1 is just the definition. It is happening because the =let expression is being parsed and applied to its containing context, with of course includes =let itself. I didn't know it was possible to have a function definition and application at the same time 😂.

This can be useful as a preview. I mean user can see their variable effect without adding this variable to a thought 😅

**Comment by raineorshine** [comment]
> > User-defined variables should probably be namespaced so they do not interfere with native metaprogramming attributes.
> 
> Yes, we should prevent that users enter our metaprogramming attibute as a variable name.

Ideally the user can mask most native attributes using lexical scoping. They can still use the same names, but they will just hide native attributes. However since the all operate in the same space, that could definitely cause problems when **em** toggles a specific attribute like `=sort` that it expects to behave in a certain way. Not sure how to handle that yet.

**Pull request merged**
