### PR TITLE
Initial Table View snapshot tests; optional Docker and VSCode configs

### LINKED ISSUE #1871: Table: Add snapshot test for col1 narrow + no wrap width
```
- X
  - =view
    - Table
  - A
    - Atlanta, Georgia
  - B
    - Boston, Massachusetts
  - C
    - Cincinnati, Ohio
```

image

### LINKED ISSUE #1872: Table: Add snapshot test for col2 narrow + no wrap width
```
- X
  - =view
    - Table
  - All of Us Strangers
    - 4/5
  - Eileen
    - 2/5
  - May December
    - 2/5
```

image

### PR DESCRIPTION
**Pull request by mathiscode**
This PR resolves #1871 and resolves #1872 by adding snapshot test cases for Table View.

Also included is a `docker-compose.yml` to allow easy running, debugging, and testing with Docker to support a more dynamic development experience since port 3000 is the default for a lot of frameworks and can often already be bound. A `.vscode/launch.json` is also included for real-time debugging with VSCode. These are optional and shouldn't affect anyone's current workflow.

To use Docker, run `npm run start:docker` or `docker compose up` and connect as normal.

### CODE REVIEW

**Review by raineorshine — CHANGES_REQUESTED** [review]
> This PR resolves #1871 and resolves #1872 by adding snapshot test cases for Table View.

Looks pretty good. Let's just generate a single snapshot for the default font size (18). It's not necessary to render it at multiple font sizes to prove the table view is rendered correctly.

The only issue I see is that the first column in the [no wrap](https://github.com/mathiscode/em/blob/main/src/e2e/puppeteer/__tests__/__image_snapshots__/ubuntu/snapshot-ts-src-e-2-e-puppeteer-tests-snapshot-ts-font-size-18-default-table-view-col-2-narrow-no-wrap-width-1-snap.png) snapshot is wrapping, which is not what we want to test. Maybe this is due to the puppeteer window being too narrow. We could decrease the font size to prevent it from wrapping, but we really ought to use a window width that will pass at the default font size. 

> Also included is a `docker-compose.yml` to allow easy running, debugging, and testing with Docker to support a more dynamic development experience since port 3000 is the default for a lot of frameworks and can often already be bound. A `.vscode/launch.json` is also included for real-time debugging with VSCode. These are optional and shouldn't affect anyone's current workflow.

A lighter weight solution here would be to add a VITE_PORT option to the vite server config. You can see how to read from env in the vite config here: https://stackoverflow.com/questions/66389043/how-can-i-use-vite-env-variables-in-vite-config-js

**Comment by raineorshine** [comment]
FYI I will be merging your changes into the [table2](https://github.com/cybersemics/em/tree/table2) branch during your trial period.

**Comment by mathiscode** [comment]
Dividers should render as expected now, which should resolve #543

**Review by raineorshine — APPROVED** [review]

**Review by raineorshine — CHANGES_REQUESTED** [review]
I'm seeing an error in the terminal when I run `npm run test:puppeteer`:

```
WebSocket server error: Port is already in use (x2)
```

I'm not sure if it affects the tests, but I can confirm that it does not occur in `main`.

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
