### PR TITLE
Move Superscript num from left by 3px

### PR DESCRIPTION
**Pull request by y471n**
#252

### CODE REVIEW

**Comment by raineorshine** [comment]
If! If you could just ensure your editor does not reformat the CSS file that would be great. Indentation, single quotes, etc are all there for a reason.

**Comment by raineorshine** [comment]
@y471n Hi! Just wanted to check in and see if you are able to follow through on this.

**Comment by y471n** [comment]
@raineorshine  Yes. Sorry, was busy elsewhere. Undid the formatting changes. Please re-review.

**Comment by raineorshine** [comment]
Thanks!

**Pull request merged**
