### PR TITLE
Switch to yarn

### PR DESCRIPTION
**Pull request by mekanix**
I tried reverting package.json and package-lock.json to those in 0082d656bace95ebf58e964911cf6385d8f9a9a7 (predating react-script update), but it gave even weirder errors, no matter if I nuke node_modules before it or not.

With `yarn` I managed to at least finish the build. I don't know if it's acceptable solution, so @raineorshine please advise.

This PR replaces #292

### CODE REVIEW

**Comment by raineorshine** [comment]
I don't believe locking the dependencies with yarn.lock or package-lock.json will work. What happens when we need to install a new dependency? The lock file may be helpful for getting that exact build to work across platforms, but I don't see how we'll be able to continue development if upgrading node modules doesn't work. Am I thinking about that correctly?

**Comment by mekanix** [comment]
It's not about the lock files for either yarn or npm. I tried reverting package-lock.json to check if some new version of some lib causes the problems for build, but no matter what I do I can't build with npm, so out of desperation I tried yarn. So in short, lock files has nothing to do with success of the build, the package manager does. I know it shouldn't be the case, but I have no idea where to look next.

**Comment by raineorshine** [comment]
I see. Thanks for explaining. So on your machine, `npm build` is not working, am I understanding that correctly? If so, maybe a docker or other container will work for you?

**Comment by mekanix** [comment]
If it's only me, we can ignore it. If I ever need build, I'll do it in a VM or Docker or something. The question is does it work for the rest?

**Comment by raineorshine** [comment]
Sounds good. I will test to see if switching to yarn and reverting react-scripts together fixes the issue on iPhone.

**Comment by mekanix** [comment]
Can you try without reverting react-scripts, first? I suspect they are not the problem.

**Comment by raineorshine** [comment]
Okay, will do.

**Pull request closed without merging**
