### PR TITLE
Recently Edited Tree key Encoding Fix

### PR DESCRIPTION
**Pull request by shresthabijay**
refers to #454

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine  I have used `hashThought` instead of firebase encode. It works properly. I tested it by passing thoughts with value of length more than 1000.

Please review it and let me know!

**Comment by raineorshine** [comment]
Is there a reason you didn't use `hashContext` as suggested? It will likely be a cache hit on the memoizer since `contextIndex` already uses it. It also may help debugging to use the same hash as the `contextIndex`.

**Comment by shresthabijay** [comment]
> Is there a reason you didn't use `hashContext` as suggested? It will likely be a cache hit on the memoizer since `contextIndex` already uses it. It also may help debugging to use the same hash as the `contextIndex`.

We want to encode each key of the `recentlyEditedTree` object tree.  Since we use value of the thought as the key not the path , it is better to use `hashThought`. Also I tried using `hashContext`, it caused lot of unwanted errors.

**Comment by raineorshine** [comment]
Ah, I see! That makes sense. I thought `contextEncode` generated a single hash some reason, but rather it maps the context to an array of hashes. Thanks!

**Pull request merged**
