### PR TITLE
hamburger zIndex fix

### PR DESCRIPTION
**Pull request by shresthabijay**
refers to #418

### CODE REVIEW

**Comment by shresthabijay** [comment]
I have changed hamburger menus `zIndex` to -1 on both tutorial and error. And also I have removed transition effect  on tutorial and error state to prevent delay on lowering of `zIndex` .

**Comment by raineorshine** [comment]
Thanks! Is there a reason the z-index is set to `-1` instead of hiding it or not rendering it?

**Comment by shresthabijay** [comment]
> Thanks! Is there a reason the z-index is set to `-1` instead of hiding it or not rendering it?

When sidebar is closed we need to delay appearing of hamburger menu using zIndex transition. But we can hide hamburger menu specifically on tutorial and error. Should we hide it?

**Comment by raineorshine** [comment]
I guess either one will work, so no preference.

Please change the draft status if you believe it is ready to be merged. Thanks!

**Pull request merged**
