### PR TITLE
React v17

### PR DESCRIPTION
**Pull request by raineorshine**
Use https://github.com/wojtekmaj/enzyme-adapter-react-17 and upgrade to React v17.

### CODE REVIEW

**Comment by raineorshine** [comment]
@shresthabijay `@bit/mui-org.material-ui.swipeable-drawer` has a peer dependency of react `^16.8.0` which is preventing us from upgrading React.

https://bit.dev/mui-org/material-ui/swipeable-drawer

Do you have experience with bit.dev? It appears to be an entire development workflow for components. I'm not sure how to fork a component in that system.

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.0
npm ERR! node_modules/react
npm ERR!   react@"17.0.0" from the root project
npm ERR!   peer react@">=16.3" from react-contenteditable@3.3.5
npm ERR!   node_modules/react-contenteditable
npm ERR!     react-contenteditable@"^3.3.5" from the root project
npm ERR!   18 more (react-dnd, react-dnd-test-utils, react-error-boundary, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @bit/mui-org.material-ui.backdrop@4.9.10
npm ERR! node_modules/@bit/mui-org.material-ui.backdrop
npm ERR!   @bit/mui-org.material-ui.backdrop@"4.9.10" from @bit/mui-org.material-ui.drawer@4.9.10
npm ERR!   node_modules/@bit/mui-org.material-ui.drawer
npm ERR!     @bit/mui-org.material-ui.drawer@"4.9.10" from @bit/mui-org.material-ui.swipeable-drawer@4.9.10
npm ERR!     node_modules/@bit/mui-org.material-ui.swipeable-drawer
npm ERR!       @bit/mui-org.material-ui.swipeable-drawer@"^4.9.10" from the root project
npm ERR!   @bit/mui-org.material-ui.backdrop@"4.9.10" from @bit/mui-org.material-ui.modal@4.9.10
npm ERR!   node_modules/@bit/mui-org.material-ui.modal
npm ERR!     @bit/mui-org.material-ui.modal@"4.9.10" from @bit/mui-org.material-ui.drawer@4.9.10
npm ERR!     node_modules/@bit/mui-org.material-ui.drawer
npm ERR!       @bit/mui-org.material-ui.drawer@"4.9.10" from @bit/mui-org.material-ui.swipeable-drawer@4.9.10
npm ERR!       node_modules/@bit/mui-org.material-ui.swipeable-drawer
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by raineorshine** [comment]
I asked how to fork a bit.dev component here: https://stackoverflow.com/questions/67948136/what-s-the-bit-dev-equivalent-of-forking-a-repo-and-submitting-a-pr

Worst case we can copy the contents of `./node_modules/@bit/mui-org.material-ui.swipeable-drawer` to a new repo and make the change there.

**Comment by raineorshine** [comment]
Never mind, npm install is working now for some reason! This is awesome, we can bring `react` and `react-native-web` up to latest.

**Comment by shresthabijay** [comment]
> @shresthabijay `@bit/mui-org.material-ui.swipeable-drawer` has a peer dependency of react `^16.8.0` which is preventing us from upgrading React.
> 
> https://bit.dev/mui-org/material-ui/swipeable-drawer
> 
> Do you have experience with bit.dev? It appears to be an entire development workflow for components. I'm not sure how to fork a component in that system.
> 
> The CI won't run because I temporarily deleted the `package-lock.json` until the peer dependencies are resolved, but you can pull the branch down and try to do an `npm install`:
> 
> ```shell
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! Found: react@17.0.0
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.0" from the root project
> npm ERR!   peer react@">=16.3" from react-contenteditable@3.3.5
> npm ERR!   node_modules/react-contenteditable
> npm ERR!     react-contenteditable@"^3.3.5" from the root project
> npm ERR!   18 more (react-dnd, react-dnd-test-utils, react-error-boundary, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0" from @bit/mui-org.material-ui.backdrop@4.9.10
> npm ERR! node_modules/@bit/mui-org.material-ui.backdrop
> npm ERR!   @bit/mui-org.material-ui.backdrop@"4.9.10" from @bit/mui-org.material-ui.drawer@4.9.10
> npm ERR!   node_modules/@bit/mui-org.material-ui.drawer
> npm ERR!     @bit/mui-org.material-ui.drawer@"4.9.10" from @bit/mui-org.material-ui.swipeable-drawer@4.9.10
> npm ERR!     node_modules/@bit/mui-org.material-ui.swipeable-drawer
> npm ERR!       @bit/mui-org.material-ui.swipeable-drawer@"^4.9.10" from the root project
> npm ERR!   @bit/mui-org.material-ui.backdrop@"4.9.10" from @bit/mui-org.material-ui.modal@4.9.10
> npm ERR!   node_modules/@bit/mui-org.material-ui.modal
> npm ERR!     @bit/mui-org.material-ui.modal@"4.9.10" from @bit/mui-org.material-ui.drawer@4.9.10
> npm ERR!     node_modules/@bit/mui-org.material-ui.drawer
> npm ERR!       @bit/mui-org.material-ui.drawer@"4.9.10" from @bit/mui-org.material-ui.swipeable-drawer@4.9.10
> npm ERR!       node_modules/@bit/mui-org.material-ui.swipeable-drawer
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ```

Sorry for responding late. Is it working now ?

**Comment by raineorshine** [comment]
Yes, it is working and merged into `dev`!

**Comment by raineorshine** [comment]
I did get a message from someone in their Slack in case we need to pursue this in the future:

> `bit import` is probably what you're looking for. https://docs.bit.dev/docs/sourcing-components
> 
> And instead of existing back to the original scope, export your updated version to your own scope. (Scope <=> collection)
> 
> As the component you're looking to fork is a legacy (i.e. non-harmony) component, please ensure you're using bit v14.x.x to so this.

**Pull request merged**
