### PR TITLE
Fix gesture diagram

### PR DESCRIPTION
**Pull request by enukeabhi**
#194

### CODE REVIEW

**Comment by raineorshine** [comment]
It appears that this PR has something to do with bullet positioning rather than the GestureDiagram. Can you explain? Thanks!

**Comment by enukeabhi** [comment]
As per the reported issue - "The GestureDiagram is too small in several places. Increase size of GestureDiagram to match the surrounding text while maintaining good spacing"

The screenshot and description pointed towards the Bullet points, so design has been updated.

Did I get it wrong?

**Comment by enukeabhi** [comment]
> It appears that this PR has something to do with bullet positioning rather than the GestureDiagram. Can you explain? Thanks!

As per the reported issue - "The GestureDiagram is too small in several places. Increase size of GestureDiagram to match the surrounding text while maintaining good spacing"

The screenshot and description pointed towards the Bullet points, so design has been updated.

Did I get it wrong?

**Comment by raineorshine** [comment]
Yes, I think you misunderstood. `GestureDiagram` is an svg component. It is not related to bullets. The relevant part of the screenshot is the "Swipe to add to a new context" and "Swipe to return to the normal view." Those instructions contain the GestureDiagrams that are too small to see.

Make sure that the GestureDiagram size is adjusted in all three places referenced in the original issue. Let me know if you have trouble finding them.

**Comment by enukeabhi** [comment]
> Yes, I think you misunderstood. `GestureDiagram` is an svg component. It is not related to bullets. The relevant part of the screenshot is the "Swipe to add to a new context" and "Swipe to return to the normal view." Those instructions contain the GestureDiagrams that are too small to see.
> 
> Make sure that the GestureDiagram size is adjusted in all three places referenced in the original issue. Let me know if you have trouble finding them.

I have fixed this. Please have a look.

**Comment by raineorshine** [comment]
Thank you! Looks good. Please rebase on dev so I can merge.

**Comment by enukeabhi** [comment]
> Thank you! Looks good. Please rebase on dev so I can merge.

I have rebased with dev. Please merge.

**Pull request merged**
