### PR TITLE
Drag Error Divider Fix

### LINKED ISSUE #777: Drag error: "Cannot move the em context to another context"
## Steps to Reproduce

- a
  - b
  - c
  - --- (divider)

Drag `b` in between `c` and `---`.

## Current Behavior

The highlighted drop target appears too far to the left. Then when dropped, there is the message: "Cannot move the em context to another context."

## Expected Behavior

The drop target should appear in between `c` and `---` and allow `b` to be dropped there.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #777

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine The issue was that the margin left of the `Divider` component didn't match that `Editable` component. So I added required margin left to the `drop-hover` if thought is a divider. The cannot move error was because there was a condition to prevent drop if the thought is a divider. Please review the changes. Thanks!

**Comment by shresthabijay** [comment]
> I would advise more caution around removing branches of logic. It's usually there for a reason. This one was added in [28b004c](https://github.com/cybersemics/em/commit/28b004c9ecd16fdc6b59ee0f1b4830fac27fe1b7), although it appears that perhaps the condition was only needed in `Subthoughts`. Until you understand the reason it was put there, you don't know for sure that you're not removing something that is needed. I recommend the use of git blame in the GitHub interface to find the commit in which a line of code was added. That can reveal the purpose and help you better evaluate its necessity.
> 
> If you are aware of this, my apologies. I read, perhaps wrongly, from your comment that you had not identified when the code was added and for what purpose.

I was aware of this. This condition was added to `Thoughts` to prevent dragging thoughts into divider. But that condition is only necessary for drop target inside  `Subthought` component.

**Comment by raineorshine** [comment]
> I was aware of this. This condition was added to `Thoughts` to prevent dragging thoughts into divider. But that condition is only necessary for drop target inside `Subthought` component.

Great! When you describe the cause ("there was a condition to prevent drop if the thought is a divider") just go one step further and describe the reason why it is not needed. Otherwise I have to do the work of tracking it down that perhaps you have already done. Thanks!

**Comment by shresthabijay** [comment]
> Great! When you describe the cause ("there was a condition to prevent drop if the thought is a divider") just go one step further and describe the reason why it is not needed. Otherwise I have to do the work of tracking it down that perhaps you have already done. Thanks!

I will keep that in mind.

**Comment by shresthabijay** [comment]
> It looks like there is a slightly different case that still causes the error. In the following, drag `c` under the divider and slightly to the right:

I will look into it.

**Comment by shresthabijay** [comment]
@raineorshine There are three drop targets responsible for showing `drop-hover`. With the `Divider` component the `drop-hover` associated with `EmptyChildrenDropTarget` doesn't have enough margin left to appear as drop target to add subthought. So it was causing confusion. I made changes to add the margin. But with `Divider` component we do not want to activate `drop-target` associated with `EmptyChildrenDropTarget` because we don't allow to drag into `Divider` thoughts anyways. So I made necessary changes to the `canDrop` logic to prevent to prevent drag if thought is a divider. Please review the changes. Thanks!

**Comment by raineorshine** [comment]
Great! That was tricky. Thank you for working through the details and getting to a solution. Excellent work.

**Pull request merged**
