### PR TITLE
Bump react-dnd version from v11.1.3 to 13.0.0

### PR DESCRIPTION
**Pull request by Zubair286**
#1839

### CODE REVIEW

**Review by raineorshine — CHANGES_REQUESTED** [review]
Looks like the build script is broken.

**Comment by Zubair286** [comment]
Not sure,`npm run build` does not throw any errors.

**Comment by raineorshine** [comment]
I'm not sure, but I get the same error on my machine.

```
Run yarn build
yarn run v1.22.22
$ vite build
vite v5.3.5 building for production...
transforming...
✓ 155[6](https://github.com/cybersemics/em/actions/runs/10308875818/job/28537280906?pr=2250#step:5:7) modules transformed.
x Build failed in 3.43s
error during build:
[vite-plugin-pwa:build] src/components/DragAndDropContext.tsx (4:[7](https://github.com/cybersemics/em/actions/runs/10308875818/job/28537280906?pr=2250#step:5:8)): "default" is not exported by "node_modules/react-dnd-multi-backend/dist/esm/index.js", imported by "src/components/DragAndDropContext.tsx".
file: /Users/runner/work/em/em/src/components/DragAndDropContext.tsx:4:7

2: import { DndProvider } from 'react-dnd'
3: import { HTML5Backend } from 'react-dnd-html5-backend'
4: import MultiBackend, { TouchTransition } from 'react-dnd-multi-backend'
          ^
5: import { TouchBackend } from 'react-dnd-touch-backend'
6: import { TIMEOUT_LONG_PRESS_THOUGHT } from '../constants'

    at getRollupError (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:3[8](https://github.com/cybersemics/em/actions/runs/10308875818/job/28537280906?pr=2250#step:5:9)8:42)
    at Module.error (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13[9](https://github.com/cybersemics/em/actions/runs/10308875818/job/28537280906?pr=2250#step:5:10)58:16)
    at Module.traceVariable (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14406:29)
    at ModuleScope.findVariable (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:121[10](https://github.com/cybersemics/em/actions/runs/10308875818/job/28537280906?pr=2250#step:5:11):39)
    at ReturnValueScope.findVariable (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
    at FunctionBodyScope.findVariable (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
    at Identifier.bind (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:6941:40)
    at Property.bind (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
    at ObjectExpression.bind (file:///Users/runner/work/em/em/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by Zubair286** [comment]
I got this error as well but, I deleted my yarn.lock and reinstalled and it went away. This error is from a future version of react-dnd, but we are on v12 right now.

**Comment by Zubair286** [comment]
Should I delete and create new and push?

**Comment by raineorshine** [comment]
Yes, I can confirm the yarn.lock is wrong. Normally it's not necessary to regenerate it from scratch, so this seems like a bug in yarn. But try uploading a new one and if all the tests pass then we can keep it.

**Comment by raineorshine** [comment]
I just regenerated yarn.lock from scratch, and unfortunately I still get the same build error. It must be either a breaking change, or an incompatibility between react-dnd and the react-dnd backend versions that are installed.

**Comment by Zubair286** [comment]
Let me see, which version of react-multi-backend-dnd is compatible with react-dnd v12.

**Comment by Zubair286** [comment]
Doesn't seem to be working here.

One thing can be done, is that I push all the commits from v11 to v16 to this PR, then the issue should probably not occur.

**Comment by raineorshine** [comment]
Try upgrading to v13 before going all the way to v16.

**Review by raineorshine — APPROVED** [review]

**Comment by raineorshine** [comment]
That solved the build issue.

Just looks like the puppeteer tests are failing now.

**Comment by Zubair286** [comment]
> That solved the build issue.
> 
> Just looks like the puppeteer tests are failing now.

Seems to me the hook timeout issue, it wasn't happening before at least on github and upgrading react-dnd shouldn't have any affect on it I think.

**Comment by raineorshine** [comment]
I re-ran the GitHub action, but it is still failing.

**Comment by Zubair286** [comment]
It seems to be giving a warning related to an `id` for the backends, let me see if that is causing them to fail.

**Comment by raineorshine** [comment]
On my machine the puppeteer tests pass against the dev server, but fail against the production build.

Close the dev server and run `npm run build && npm run:servebuild` to build and launch the production server. That's what GitHub Actions uses.

**Comment by Zubair286** [comment]
Running production server gives this error on console hence the test fails.
image

**Comment by raineorshine** [comment]
Production-only bugs are annoyingly difficult to debug 😕

At least you can reproduce it now.

**Comment by Zubair286** [comment]
Yeah, I'll see what I can do about it.

**Comment by Zubair286** [comment]
@raineorshine the issue is fixed, can you please rename the PR to v11.1.3 to 13.0.0?

**Review by raineorshine — APPROVED** [review]

**Pull request merged**
