### PR TITLE
Hidden thoughts should be not draggable

### PR DESCRIPTION
**Pull request by incora-dev**
#452

### CODE REVIEW

**Comment by raineorshine** [comment]
Is this PR still in progress?

**Comment by incora-dev** [comment]
> Is this PR still in progress?

This task is completed

**Comment by raineorshine** [comment]
> > Is this PR still in progress?
> 
> This task is completed

And you have tested it thoroughly, and dragging is working in all circumstances as far as you can tell?

**Comment by incora-dev** [comment]
> And you have tested it thoroughly, and dragging is working in all circumstances as far as you can tell?

Now it should works

**Comment by raineorshine** [comment]
Thank you. Just one case I found that's not working:

- a [hidden]
- b
  - x
    - y [cursor]

`b` should be draggable.

**Comment by raineorshine** [comment]
It appears that 3013418 makes the other hidden thoughts draggable again.

**Comment by incora-dev** [comment]
> It appears that [3013418](https://github.com/cybersemics/em/commit/3013418e137e1a4cab55df7c0e82c07a2a6e187a) makes the other hidden thoughts draggable again.

I have double-checked and it works correctly for me, could you describe when it works badly?

**Comment by raineorshine** [comment]
Yes, it looks like it is working. My apologies, I must have been looking at the wrong version!

**Pull request merged**
