### PR TITLE
Hamburger zindex fix

### PR DESCRIPTION
**Pull request by shresthabijay**
refers #541

### CODE REVIEW

**Comment by shresthabijay** [comment]
> Can you also prevent the Hamburger menu from covering modals, like the export modal? Thanks!

@raineorshine It is done.

**Comment by raineorshine** [comment]
Great!

**Comment by shresthabijay** [comment]
> Great!

@raineorshine Is help section a modal too ?

**Comment by raineorshine** [comment]
Yes

**Comment by shresthabijay** [comment]
> Yes

It is working on desktop but strangely not working for mobile. I will send another PR to fix it.

**Pull request merged**
