### PR TITLE
Fixed cursor disappear issue after indent and outdent.

### PR DESCRIPTION
**Pull request by umair-khanzada**
Ref #490

### CODE REVIEW

**Comment by raineorshine** [comment]
Hi! I think the fix actually belongs in `existingThoughtMove`. The question is, since the new cursor depends on `editing`, [why is `editing` false in this particular case](https://github.com/umair-khanzada/em/blob/14ed500535600ada0370604768da01f6a70c439d/src/reducers/existingThoughtMove.js#L186)?

**Comment by raineorshine** [comment]
I thought about it more, and I think it makes sense to dispatch a separate action. The default behavior of `existingThoughtMove` should not change the cursor unless the cursor is already on it. Drag and drop is a special case, where the cursor should follow the drop.

**Comment by umair-khanzada** [comment]
But what I am thinking it is not a good practice to dispatch two events from action-creator, we should move this in exec? what do you think?

**Comment by umair-khanzada** [comment]
> ~I thought about it more, and I think it makes sense to dispatch a separate action. The default behavior of `existingThoughtMove` should not change the cursor unless the cursor is already on it. Drag and drop is a special case, where the cursor should follow the drop.~
> 
> Never mind, this isn’t drag and drop. I would expect `editing` to be true.

So the issue is `equalPath` function returning `false` because of `cursorBeforeEdit.value` is an empty string while the `oldPath.value` is different in our case it is `'b'` that's why the editing flag is false

**Comment by raineorshine** [comment]
Replaced by #512

**Pull request closed without merging**
