### PR TITLE
Upgrade dependencies

### LINKED ISSUE #805: Upgrade dependencies
Upgrade all npm dependencies and confirm that unit tests still work. You may want to use [`npm-check-updates`](https://github.com/raineorshine/npm-check-updates/) to make this easier.

There are 19 potentially breaking upgrades at time of writing (see below). You may wish to upgrade 5-10 at a time and then reduce that number if you are getting errors in order to identify the problematic upgrade.

Make sure **em** is loading, rendering, editing, and handling swipe gestures on mobile after upgrading.

You will have to test the following manually:

- `dexie` → Make sure thoughts persist after refreshing the page
- `htmlparser2` → Paste some text into **em**
- `react-hamburger-menu` → Open the Recently Edited hamburger menu
- `typedoc` → `npm run docs` and open `/docs/index.html`

If an upgrade breaks, take a look at their changelog and see how much work it will require to upgrade on our end. I use `npm view PACKAGE_NAME homepage | xargs open` to open the home page of a package and then look for a `CHANGELOG.md` or `HISTORY.md`. If it's a trivial change, go ahead and fix it, otherwise report here what the dependency is and what it would entail to fix it. We can add the dependency to the `.ncurc` temporarily and track the upgrade in a separate issue.

FYI, we already know that `react-dnd` is breaking, so you can leave that as-is (per the [`.ncurc`](https://github.com/cybersemics/em/blob/dev/.ncurc.json)).

```
$ ncu
Checking /Users/raine/projects/em/package.json

 @bit/mui-org.material-ui.swipeable-drawer     ^4.5.2  →    ^4.9.10 
 dexie                                         ^2.0.4  →     ^3.0.1 
 htmlparser2                                  ^3.10.1  →     ^4.1.0 
 immer                                         ^5.3.6  →     ^7.0.5 
 ipfs-http-client                             ^43.0.1  →    ^45.0.0 
 lodash                                      ^4.17.15  →   ^4.17.19 
 moment                                       ^2.22.2  →    ^2.27.0 
 react                                       ^16.13.0  →   ^16.13.1 
 react-click-n-hold                            ^1.0.6  →     ^1.0.7 
 react-contenteditable                         ^3.3.3  →     ^3.3.5 
 react-dom                                   ^16.13.0  →   ^16.13.1 
 react-error-boundary                          ^2.2.1  →     ^2.2.3 
 react-hamburger-menu                          ^1.1.1  →     ^1.2.1 
 react-native-web                             ^0.12.0  →    ^0.13.4 
 react-redux                                   ^7.1.3  →     ^7.2.0 
 react-scripts                                 ^3.4.0  →     ^3.4.1 
 react-split-pane                             ^0.1.89  →    ^0.1.91 
 react-transition-group                        ^4.3.0  →     ^4.4.1 
 static-eval                                   ^2.0.3  →     ^2.1.0 
 ts-key-enum                                   ^2.0.2  →     ^2.0.3 
 typescript                                    ^3.7.5  →     ^3.9.7 
 uuid                                          ^3.4.0  →     ^8.2.0 
 @types/classnames                             ^2.2.9  →    ^2.2.10 
 @types/jest                                  ^24.0.0  →    ^26.0.5 
 @types/lodash                              ^4.14.150  →  ^4.14.157 
 @types/node                                  ^13.7.4  →   ^14.0.23 
 @types/node-sass                             ^4.11.0  →    ^4.11.1 
 @types/react                                 16.9.19  →    16.9.43 
 @types/react-dom                              16.9.5  →     16.9.8 
 @types/react-redux                            ^7.1.7  →     ^7.1.9 
 @types/react-transition-group                 ^4.2.4  →     ^4.4.0 
 @typescript-eslint/eslint-plugin              ^3.0.2  →     ^3.7.0 
 @typescript-eslint/parser                     ^3.0.2  →     ^3.7.0 
 eslint                                        ^6.8.0  →     ^7.5.0 
 eslint-config-airbnb-typescript               ^7.0.0  →     ^9.0.0 
 eslint-config-standard                       ^14.1.0  →    ^14.1.1 
 eslint-plugin-import                         ^2.19.1  →    ^2.22.0 
 eslint-plugin-jsdoc                          ^25.4.2  →    ^30.0.2 
 eslint-plugin-jsx-a11y                        ^6.2.3  →     ^6.3.1 
 eslint-plugin-node                           ^10.0.0  →    ^11.1.0 
 eslint-plugin-react                          ^7.17.0  →    ^7.20.3 
 eslint-plugin-react-hooks                     ^2.4.0  →     ^4.0.8 
 fake-indexeddb                                ^3.0.0  →     ^3.1.1 
 jest-localstorage-mock                        ^2.4.0  →     ^2.4.3 
 raw.macro                                     ^0.3.1  →     ^0.4.0 
 typedoc                                      ^0.17.7  →    ^0.17.8 
 typedoc-plugin-module-wide-comments            0.0.1  →      1.0.3 
 xml2json                                     ^0.11.2  →    ^0.12.0 

Run ncu -u to upgrade package.json
```

### PR DESCRIPTION
**Pull request by aqkhan**
Fixes #805

### CODE REVIEW

**Comment by aqkhan** [comment]
All the dependencies have been updated using `npm-check-updates` as reference. 

The application is loading, rendering, editing, and handling swipe gestures on mobile after upgrading. Also, I've tested the following manually before and after upgrading the packages:
- `dexie` → Make sure thoughts persist after refreshing the page
- `htmlparser2` → Paste some text into em
- `react-hamburger-menu` → Open the Recently Edited hamburger menu
- `typedoc` → npm run docs and open /docs/index.html

PS: I have disabled the `ArrowFunctionExpression` in `jsdoc/require-jsdoc` as it was throwing errors for missing JSDoc comments. Do let me know if I should add comments to appropriate places.

**Comment by raineorshine** [comment]
> All the dependencies have been updated using `npm-check-updates` as reference.

Great, thanks!

> PS: I have disabled the `ArrowFunctionExpression` in `jsdoc/require-jsdoc` as it was throwing errors for missing JSDoc comments. Do let me know if I should add comments to appropriate places.

Interesting, I'm not sure what would have caused this change. All of the functions in the app are declared as `ArrowFunctionExpressions`, so if you disable it then we won't have JSDoc enforcement on any function. Please re-enable and fill in any missing JSDoc comments. For highly canonical functions like `mapStateToProps` you can add a `@ts-ignore` statement since the comment would not add anything useful.

**Comment by aqkhan** [comment]
@raineorshine Acknowledged!

**Comment by aqkhan** [comment]
@raineorshine `@ts-ignore` didn't seem to work. I've used `eslint-disable-next-line` instead.

**Comment by raineorshine** [comment]
> Please re-enable and fill in any missing JSDoc comments.

I'm not sure how you interpreted the above statement as "disable all arrow function expressions"...?  I didn't suggest that at any point. You basically converted a single line that disables `ArrowFunctionExpressions` to a distributed set of comments that disables exactly the same code. This seems like a poor judgment call.

That said, I didn't realize that they were all callbacks. JSDOC comments on callbacks seem unnecessary. 

Does `ArrowFunctionExpression` also target `const foo = (x, y) => ...`? We need a way to enforce JSDOC comments on functions declared via arrow syntax, but exclude callbacks.

**Comment by aqkhan** [comment]
@raineorshine 

> For highly canonical functions like mapStateToProps you can add a @ts-ignore statement since the comment would not add anything useful.

I added `eslint-disable-next-line` instead of `@ts-ignore` here, since the arrow functions causing issues were too generic to have a meaningful comment. 

> Does ArrowFunctionExpression also target const foo = (x, y) => ...?

And yes it does, and apparently it appeared after the update. 

> We need a way to enforce JSDOC comments on functions declared via arrow syntax, but exclude callbacks.

Agreed.

**Comment by raineorshine** [comment]
We know it was caused by a breaking change from one of the eslint packages. I recommend identifying which upgrade broke it. Then they may have a change log that offers a migration pattern.

**Comment by aqkhan** [comment]
@raineorshine I wasn't able to find the breaking change that caused the aforementioned issue, mainly due to the lack of a proper changelog for `eslint-plugin-jsdoc`. I have referred to their release docs: https://github.com/gajus/eslint-plugin-jsdoc/releases. I will more time to determine the breaking change and put a fix in place.

**Comment by aqkhan** [comment]
New [PR](https://github.com/cybersemics/em/pull/886) opened for #805.

**Pull request closed without merging**
